// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from "@hey-api/client-fetch";
import type {
  SignupData,
  SignupResponse,
  SignupError,
  SigninData,
  SigninResponse,
  SigninError,
  RefreshTokenData,
  RefreshTokenResponse,
  SignoutData,
  SignoutResponse,
  GetCurrentUserData,
  GetCurrentUserResponse,
  RootData,
  RootResponse,
  RootError,
} from "./types.gen";

export const client = createClient(createConfig());

export class AuthService {
  /**
   * Signup
   */
  public static signup<ThrowOnError extends boolean = false>(options: Options<SignupData, ThrowOnError>) {
    return (options?.client ?? client).post<SignupResponse, SignupError, ThrowOnError>({
      url: "/auth/signup",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Signin
   */
  public static signin<ThrowOnError extends boolean = false>(options: Options<SigninData, ThrowOnError>) {
    return (options?.client ?? client).post<SigninResponse, SigninError, ThrowOnError>({
      url: "/auth/signin",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Refresh Token
   */
  public static refreshToken<ThrowOnError extends boolean = false>(options?: Options<RefreshTokenData, ThrowOnError>) {
    return (options?.client ?? client).post<RefreshTokenResponse, unknown, ThrowOnError>({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/auth/refresh-token",
      ...options,
    });
  }

  /**
   * Signout
   */
  public static signout<ThrowOnError extends boolean = false>(options?: Options<SignoutData, ThrowOnError>) {
    return (options?.client ?? client).post<SignoutResponse, unknown, ThrowOnError>({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/auth/signout",
      ...options,
    });
  }

  /**
   * Get Current User
   */
  public static getCurrentUser<ThrowOnError extends boolean = false>(
    options?: Options<GetCurrentUserData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<GetCurrentUserResponse, unknown, ThrowOnError>({
      security: [
        {
          scheme: "bearer",
          type: "http",
        },
      ],
      url: "/auth/me",
      ...options,
    });
  }
}

export class DefaultService {
  /**
   * Root
   */
  public static root<ThrowOnError extends boolean = false>(options: Options<RootData, ThrowOnError>) {
    return (options?.client ?? client).get<RootResponse, RootError, ThrowOnError>({
      url: "/",
      ...options,
    });
  }
}
