services:
  db:
    image: postgres:16.2
    container_name: wallstr_db
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password123
    ports:
      - 5441:5432

  redis:
    image: redis:7-alpine
    container_name: wallstr_redis
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: wallstr_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password123
    ports:
      - 5672:5672

  minio:
    image: minio/minio:latest
    container_name: wallstr_minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password123
    ports:
      - 9000:9000
      - 9001:9001